### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by marcotroisi** [microlib/usermanager#7]
basic Travis configuration for running go tests

**Comment by marcotroisi** [comment]
``` yaml
language: go

go:
  - 1.6
  - tip

go_import_path: github.com/microlib/usermanager

script:
  - go test ./...
```
